export type Dress = {
  id: string
  slug: string
  name: { he: string; en: string }
  fabric: { he: string; en: string }
  description: { he: string; en: string }
  image: string       // main card image
  images: string[]    // all gallery images
  video?: string      // optional mp4 video
  featured: boolean
  tags: { he: string[]; en: string[] }
  silhouette: { he: string; en: string }
}

export const dresses: Dress[] = [
  {
    id: '1',
    slug: 'dress-1',
    name: { he: 'לומייר', en: 'Lumière' },
    fabric: { he: 'משי שמפניה', en: 'Champagne Silk' },
    description: {
      he: 'קו A עדין עם שרוולים ארוכים של קרפ ומחשוף V אלגנטי. פשוטה. מושלמת.',
      en: 'Delicate A-line with long crepe sleeves and an elegant V-neckline. Simple. Perfect.',
    },
    image: '/dresses/1/DSCF0011.jpg',
    images: [
      '/dresses/1/DSCF0011.jpg',
      '/dresses/1/DSCF0020 — копия.jpg',
      '/dresses/1/DSCF0026.jpg',
      '/dresses/1/DSCF4001.jpg',
      '/dresses/1/DSCF4007.jpg',
      '/dresses/1/DSCF4011.jpg',
      '/dresses/1/DSCF4013.jpg',
      '/dresses/1/DSCF4040.jpg',
      '/dresses/1/DSCF4054.jpg',
      '/dresses/1/DSCF4063.jpg',
      '/dresses/1/DSCF4064.jpg',
      '/dresses/1/DSCF4069.jpg',
      '/dresses/1/DSCF4076.jpg',
      '/dresses/1/DSCF4084.jpg',
      '/dresses/1/DSCF4089.jpg',
    ],
    video: '/dresses/1/video.mp4',
    featured: true,
    tags: { he: ['A-ליין', 'שרוולים ארוכים', 'מינימליסטי'], en: ['A-line', 'long sleeves', 'minimalist'] },
    silhouette: { he: 'A-ליין', en: 'A-line' },
  },
  {
    id: '2',
    slug: 'dress-2',
    name: { he: 'עדן', en: 'Eden' },
    fabric: { he: 'קרפ צמוד', en: 'Column Crêpe' },
    description: {
      he: 'שמלה עמודה עם מחשוף עמוק בגב. חשיפה מינימלית, אפקט מקסימלי.',
      en: 'A column gown with a deep open back. Minimal exposure, maximum impact.',
    },
    image: '/dresses/2/DSCF4118.jpg',
    images: [
      '/dresses/2/DSCF4118.jpg',
      '/dresses/2/DSCF4122.jpg',
      '/dresses/2/DSCF4123.jpg',
      '/dresses/2/DSCF4130.jpg',
      '/dresses/2/DSCF4133.jpg',
      '/dresses/2/DSCF4158.jpg',
      '/dresses/2/DSCF4160.jpg',
      '/dresses/2/DSCF4181.jpg',
      '/dresses/2/DSCF4201.jpg',
      '/dresses/2/DSCF4217.jpg',
    ],
    video: '/dresses/2/video.mp4',
    featured: true,
    tags: { he: ['עמוד', 'גב פתוח', 'נקי'], en: ['column', 'open back', 'clean'] },
    silhouette: { he: 'עמוד', en: 'Column' },
  },
  {
    id: '3',
    slug: 'dress-3',
    name: { he: 'אלבה', en: 'Alba' },
    fabric: { he: 'סאטן ויסקוזה', en: 'Viscose Satin' },
    description: {
      he: 'מחשוף מרובע, גזרה זורמת. בד סאטן שנע עם הגוף — לא מתנגד לו.',
      en: 'Square neckline, fluid drape. Satin that moves with the body — not against it.',
    },
    image: '/dresses/3/DSCF0058.jpg',
    images: [
      '/dresses/3/DSCF0058.jpg',
      '/dresses/3/DSCF0062.jpg',
      '/dresses/3/DSCF0083.jpg',
      '/dresses/3/DSCF4234.jpg',
      '/dresses/3/DSCF4245.jpg',
      '/dresses/3/DSCF4269.jpg',
      '/dresses/3/DSCF4305.jpg',
      '/dresses/3/DSCF4311.jpg',
      '/dresses/3/DSCF4321.jpg',
      '/dresses/3/DSCF4326.jpg',
      '/dresses/3/DSCF4327.jpg',
      '/dresses/3/DSCF4333.jpg',
      '/dresses/3/DSCF4412.jpg',
      '/dresses/3/DSCF4415.jpg',
    ],
    video: '/dresses/3/video.mp4',
    featured: true,
    tags: { he: ['סאטן', 'מחשוף מרובע', 'זורם'], en: ['satin', 'square neck', 'fluid'] },
    silhouette: { he: 'זורם', en: 'Fluid' },
  },
  {
    id: '4',
    slug: 'dress-4',
    name: { he: 'ריווריה', en: 'Rêverie' },
    fabric: { he: 'תחרה צרפתית עם רובה משי', en: 'French Lace with Silk Underlining' },
    description: {
      he: 'תחרה עדינה עם שרוולי בלון, מחשוף עגול, וחצאית A-ליין רחבה. רומנטיקה מדודה.',
      en: 'Delicate lace with balloon sleeves, round neckline, and full A-line skirt. Romance, measured.',
    },
    image: '/dresses/4/DSCF0088.jpg',
    images: [
      '/dresses/4/DSCF0088.jpg',
      '/dresses/4/DSCF4491.jpg',
      '/dresses/4/DSCF4504.jpg',
      '/dresses/4/DSCF4505.jpg',
      '/dresses/4/DSCF4506.jpg',
      '/dresses/4/DSCF4513.jpg',
      '/dresses/4/DSCF4515.jpg',
      '/dresses/4/DSCF4542.jpg',
      '/dresses/4/DSCF4549.jpg',
      '/dresses/4/DSCF4592.jpg',
      '/dresses/4/DSCF4594.jpg',
      '/dresses/4/DSCF4615.jpg',
      '/dresses/4/DSCF4623.jpg',
      '/dresses/4/DSCF4628.jpg',
      '/dresses/4/DSCF4643.jpg',
      '/dresses/4/DSCF4646.jpg',
    ],
    video: '/dresses/4/video.mp4',
    featured: true,
    tags: { he: ['תחרה', 'A-ליין', 'רומנטי'], en: ['lace', 'A-line', 'romantic'] },
    silhouette: { he: 'A-ליין', en: 'A-line' },
  },
  {
    id: '5',
    slug: 'dress-5',
    name: { he: 'סוארה', en: 'Soirée' },
    fabric: { he: "ג'ורג'ט משי", en: 'Silk Georgette' },
    description: {
      he: 'שמלת מעטפת עם כתפיות דקיקות. קו ישיר ונקי שמתחיל מהבד עצמו.',
      en: 'Wrap silhouette with thin straps. A clean, straight line that starts with the fabric itself.',
    },
    image: '/dresses/5/DSCF4692.jpg',
    images: [
      '/dresses/5/DSCF4692.jpg',
      '/dresses/5/DSCF4700.jpg',
      '/dresses/5/DSCF4709.jpg',
      '/dresses/5/DSCF4720.jpg',
      '/dresses/5/DSCF4748.jpg',
      '/dresses/5/DSCF4757.jpg',
      '/dresses/5/DSCF4767.jpg',
      '/dresses/5/DSCF4775.jpg',
      '/dresses/5/DSCF4778.jpg',
      '/dresses/5/DSCF4794.jpg',
      '/dresses/5/DSCF4821.jpg',
      '/dresses/5/DSCF4822.jpg',
      '/dresses/5/DSCF4839.jpg',
    ],
    video: '/dresses/5/video.mp4',
    featured: false,
    tags: { he: ['כתפיות', 'מעטפת', 'קל'], en: ['straps', 'wrap', 'light'] },
    silhouette: { he: 'מעטפת', en: 'Wrap' },
  },
  {
    id: '6',
    slug: 'dress-6',
    name: { he: 'מירואר', en: 'Miroir' },
    fabric: { he: 'אורגנזה משי', en: 'Silk Organza' },
    description: {
      he: 'גזרת בלון עם חצאית בועה קלה. שמלה שמביאה שמחה פנימה לאירוע.',
      en: 'Balloon silhouette with a light bubble skirt. A gown that brings joy to the occasion.',
    },
    image: '/dresses/6/DSCF4872.jpg',
    images: [
      '/dresses/6/DSCF4872.jpg',
      '/dresses/6/DSCF4876.jpg',
      '/dresses/6/DSCF4883.jpg',
      '/dresses/6/DSCF4887.jpg',
      '/dresses/6/DSCF4917.jpg',
      '/dresses/6/DSCF4926.jpg',
      '/dresses/6/DSCF4932.jpg',
      '/dresses/6/DSCF4949.jpg',
      '/dresses/6/DSCF4950.jpg',
      '/dresses/6/DSCF4952.jpg',
      '/dresses/6/DSCF4979.jpg',
      '/dresses/6/DSCF4987.jpg',
      '/dresses/6/DSCF4990.jpg',
    ],
    video: '/dresses/6/video.mp4',
    featured: false,
    tags: { he: ['אורגנזה', 'בועה', 'שמח'], en: ['organza', 'bubble', 'joyful'] },
    silhouette: { he: 'בועה', en: 'Bubble' },
  },
  {
    id: '7',
    slug: 'dress-7',
    name: { he: 'אורה', en: 'Aura' },
    fabric: { he: 'שיפון עדין', en: 'Delicate Chiffon' },
    description: {
      he: 'שמלה זורמת עם שכבות עדינות של שיפון. תנועה קסומה בכל צעד.',
      en: 'A flowing gown with delicate chiffon layers. Magical movement with every step.',
    },
    image: '/dresses/7/DSCF5101.jpg',
    images: [
      '/dresses/7/DSCF5101.jpg',
      '/dresses/7/DSCF5110.jpg',
      '/dresses/7/DSCF5112.jpg',
      '/dresses/7/DSCF5117.jpg',
      '/dresses/7/DSCF5122.jpg',
      '/dresses/7/DSCF5148.jpg',
      '/dresses/7/DSCF5154.jpg',
      '/dresses/7/DSCF5191.jpg',
      '/dresses/7/DSCF5200.jpg',
      '/dresses/7/DSCF5216.jpg',
      '/dresses/7/DSCF5247.jpg',
      '/dresses/7/DSCF5260.jpg',
      '/dresses/7/DSCF5263.jpg',
    ],
    video: '/dresses/7/video.mp4',
    featured: false,
    tags: { he: ['שיפון', 'זורם', 'עדין'], en: ['chiffon', 'fluid', 'delicate'] },
    silhouette: { he: 'זורם', en: 'Fluid' },
  },
  {
    id: '8',
    slug: 'dress-8',
    name: { he: 'בלאנש', en: 'Blanche' },
    fabric: { he: 'קרפ לבן טהור', en: 'Pure White Crêpe' },
    description: {
      he: 'עמוד נקי עם חגורה עדינה. לבן טהור שמדבר בעצמו.',
      en: 'A clean column with a subtle belt. Pure white that speaks for itself.',
    },
    image: '/dresses/8/DSCF0143.jpg',
    images: [
      '/dresses/8/DSCF0143.jpg',
      '/dresses/8/DSCF5301.jpg',
      '/dresses/8/DSCF5309.jpg',
      '/dresses/8/DSCF5311.jpg',
      '/dresses/8/DSCF5314.jpg',
      '/dresses/8/DSCF5332.jpg',
      '/dresses/8/DSCF5346.jpg',
      '/dresses/8/DSCF5355.jpg',
      '/dresses/8/DSCF5367.jpg',
      '/dresses/8/DSCF5372.jpg',
      '/dresses/8/DSCF5374.jpg',
      '/dresses/8/DSCF5375.jpg',
      '/dresses/8/DSCF5377.jpg',
    ],
    video: '/dresses/8/video.mp4',
    featured: false,
    tags: { he: ['עמוד', 'לבן', 'מינימליסטי'], en: ['column', 'white', 'minimalist'] },
    silhouette: { he: 'עמוד', en: 'Column' },
  },
  {
    id: '9',
    slug: 'dress-9',
    name: { he: 'נועה', en: 'Noa' },
    fabric: { he: 'טול עם תחרה', en: 'Tulle with Lace' },
    description: {
      he: 'שמלה רומנטית עם שכבות טול ותחרה עדינה. חלום לבן שהפך למציאות.',
      en: 'A romantic gown with tulle layers and delicate lace. A white dream made real.',
    },
    image: '/dresses/9/DSCF0167.jpg',
    images: [
      '/dresses/9/DSCF0167.jpg',
      '/dresses/9/DSCF0170.jpg',
      '/dresses/9/DSCF0171.jpg',
      '/dresses/9/DSCF5405.jpg',
      '/dresses/9/DSCF5406.jpg',
      '/dresses/9/DSCF5407.jpg',
      '/dresses/9/DSCF5418.jpg',
      '/dresses/9/DSCF5424.jpg',
      '/dresses/9/DSCF5448.jpg',
      '/dresses/9/DSCF5455.jpg',
      '/dresses/9/DSCF5464.jpg',
      '/dresses/9/DSCF5466.jpg',
      '/dresses/9/DSCF5478.jpg',
      '/dresses/9/DSCF5479.jpg',
      '/dresses/9/DSCF5519.jpg',
    ],
    video: '/dresses/9/video.mp4',
    featured: false,
    tags: { he: ['טול', 'תחרה', 'רומנטי'], en: ['tulle', 'lace', 'romantic'] },
    silhouette: { he: 'A-ליין', en: 'A-line' },
  },
  {
    id: '10',
    slug: 'dress-10',
    name: { he: 'מייה', en: 'Maya' },
    fabric: { he: 'מיקדו משי', en: 'Silk Mikado' },
    description: {
      he: 'מיקדו מבריק עם חצאית נפוחה. שילוב של כוח ועדינות.',
      en: 'Lustrous Mikado with a full skirt. The meeting of strength and softness.',
    },
    image: '/dresses/10/DSCF0189.jpg',
    images: [
      '/dresses/10/DSCF0189.jpg',
      '/dresses/10/DSCF0192.jpg',
      '/dresses/10/DSCF0214.jpg',
      '/dresses/10/DSCF5532.jpg',
      '/dresses/10/DSCF5536.jpg',
      '/dresses/10/DSCF5547.jpg',
      '/dresses/10/DSCF5582.jpg',
      '/dresses/10/DSCF5586.jpg',
      '/dresses/10/DSCF5614.jpg',
      '/dresses/10/DSCF5629.jpg',
      '/dresses/10/DSCF5666.jpg',
      '/dresses/10/DSCF5674.jpg',
      '/dresses/10/DSCF5680.jpg',
      '/dresses/10/DSCF5710.jpg',
    ],
    video: '/dresses/10/video.mp4',
    featured: false,
    tags: { he: ['מיקדו', 'נפוח', 'אלגנטי'], en: ['mikado', 'full', 'elegant'] },
    silhouette: { he: 'A-ליין', en: 'A-line' },
  },
]
